/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package es2_triangulo;

import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.Assertions;

class TriangleTest {


    @Test
    public void testTrianguloEquilatero() {
        Triangle triangulo = new Triangle(3,5,5);
        Assertions.assertEquals("equilateral",triangulo.classify());
    }
}

